var menuItems = [

    ["YOUR COMPANY","", "", "", "", "", "0", "0", "", ],
        ["|profile","menue_call.php?go=tcontacts_data.inc&func=user_profile&dir=includes", "", "", "Bearbeiten Sie Ihre Kontaktdaten", "", "", "", "", ],
        ["|password","menue_call.php?go=tcontacts_data.inc&func=user_password&dir=includes", "", "", "Neues Passwot eingeben", "", "", "", "", ],
        ["|vehicle","", "", "", "", "", "", "", "", ],
            ["||Insert","menue_call.php?go=tkfz_data.inc&func=kfz_reg&dir=includes", "", "", "Neues Fahrzeug erfassen ?", "", "", "", "", ],
            ["||Change","menue_call.php?go=tkfz_data.inc&func=kfz_list&dir=includes", "", "", "Daten eines erfassten Fahrzeugs Ã¤ndern ?", "", "", "", "", ],
        ["|drivers","", "", "", "", "", "", "", "", ],
            ["||insert","menue_call.php?go=tpartner_data.inc&func=part_new&dir=includes", "", "", "Neuen Fahrer erfassen ?", "", "", "", "", ],
            ["||change","menue_call.php?go=tpartner_data.inc&func=part_list&dir=includes", "", "", "Daten eines erfassten Fahrers Ã¤ndern ?", "", "", "", "", ],
        ["|offer a tour","", "", "", "", "", "", "", "", ],
            ["||cargo offer","menue_call.php?go=ttourkfz_data.inc&func=tourkfz_reg&dir=includes", "", "", "Fracht angebot anpassen ?", "", "", "", "", ],
            ["||change cargo offer","menue_call.php?go=ttourkfz_data.inc&func=tourkfz_list&dir=includes", "", "", "Neuen Fahrer erfassen ?", "", "", "", "", ],
            ["||vehicle offer","menue_call.php?go=ttourlad_data.inc&func=tourlad_reg&dir=includes", "", "", "Fahrzeug fÃ¼r Tour anbieten ?", "", "", "", "", ],
            ["||change vehicle offer","menue_call.php?go=ttourlad_data.inc&func=tourlad_list&dir=includes", "", "", "Fahrzeug angebot anpassen ?", "", "", "", "", ],
            ["||removal offer","menue_call.php?go=tumz_data.inc&func=umz_reg&dir=includes", "", "", "Umzug Tour anbieten ?", "", "", "", "", ],
            ["||change removal","menue_call.php?go=tumz_data.inc&func=umz_list&dir=includes", "", "", "Umzug Angebot anpassen ?", "", "", "", "", ],
        ["|account","menue_call.php?go=profil&dir=dyn", "", "", "", "", "", "", "", ],
    ["SEARCHES","", "", "", "", "", "0", "", "", ],
        ["|vehicles","menue_call.php?go=toursuchen_data.inc&func=such_list&value=kfz&dir=includes", "", "", "", "", "", "", "", ],
        ["|cargo","menue_call.php?go=toursuchen_data.inc&func=such_list&value=lad&dir=includes", "", "", "", "", "", "", "", ],
        ["|allowance for removal","menue_call.php?go=toursuchen_data.inc&func=such_list&value=umz&dir=includes", "", "", "", "", "", "", "", ],
    ["RAILWAY","", "", "", "", "", "0", "", "", ],
        ["|load cargo","", "", "", "", "_parent", "", "", "", ],
            ["||RAILION Logistics","http://www.railion.com/site/railion/en/start.html", "", "", "", "_blank", "", "", "", ],
            ["||SBB Cargo","https://cis3.sbbcargo.ch/ciso/start.do?lang=en", "", "", "", "_blank", "", "", "", ],
            ["||RAIL CARGO AUSTRIA","http://www.railcargo.at/en/index.jsp", "", "", "", "_blank", "", "", "", ],
            ["||SLOVENSKE Cargo","http://www.sz-tovornipromet.si/en/", "", "", "", "_blank", "", "", "", ],
      ["||CHINA(Peking)","menue_call.php?go=china&dir=dyn", "", "", "", "_blank", "", "", "", ],
        ["|trailer shipment","", "", "", "", "", "", "", "", ],
            ["||motorail trains","http://www.autoreisezuege-in-europa.de/", "", "", "", "_blank", "", "", "", ],
            ["||DB","http://www.dbautozug.de/site/dbautozug/en/start.html", "", "", "", "_blank", "", "", "", ],
            ["||SBB","http://mct.sbb.ch/mct/en/reiselust/europareisen/zuege-international-2/autoreisezug.htm", "", "", " ", "_blank", "", "", "", ],
       		["|deal handling","menue_call.php?go=auftrag.php&dir=dyn", "", "", "", "_parent", "", "", "", ],
     ["TRANSIT","", "", "", "", "", "0", "", "", ],
        ["|book","menue_call.php?go=trans_reser&dir=dyn", "", "", "", "", "", "", "", ],
        ["|payment of duty","menue_call.php?go=profil&dir=dyn", "", "", "", "", "", "", "", ],
        ["|officail request","menue_call.php?go=profil&dir=dyn", "", "", "", "_parent", "", "", "", ],
    ["SPONSORS","", "", "", "", "", "0", "", "", ],
        ["|info","menue_call.php?go=sponsor_info_&dir=stat", "", "", "", "", "", "", "", ],
        ["|to subscribe money","menue_call.php?go=spenden&dir=dyn", "", "", "", "_parent", "", "", "", ],
];