var tmenuItems = [
    ["ficher","menue_call.php?go=tcontacts_data.inc&func=user_reg&dir=includes", "", "", "", "Als neuer User registrieren", "", "", "", ],
    ["À NOUVEAU OFFRIR","", "", "", "", "", "", "", "", ],
           ["||cargaison ","menue_call.php?go=ttourkfz_data.inc&func=tourkfz_reg&value=quick&dir=includes", "", "", "Fracht angebot anpassen ?", "", "", "", "", ],
           ["||véhicule","menue_call.php?go=ttourlad_data.inc&func=tourlad_reg&value=quick&dir=includes", "", "", "Fahrzeug fÃƒÂ¼r Tour anbieten ?", "", "", "", "", ],
           ["||Un déménagement","menue_call.php?go=tumz_data.inc&func=umz_reg&value=quick&dir=includes", "", "", "Umzug Tour anbieten ?", "", "", "", "", ],
    ["INFO","", "", "", "", "", "", "", "", ],
             ["|DOUANE","", "", "", "", "", "", "", "", ],
            ["||Suisse","http://www.ezv.admin.ch/index.html?lang=fr", "", "", "", "", "_blank", "", "", ],
            ["||Autriche ","http://www.bmf.gv.at/zoll/_start.htm", "", "", "", "", "_blank", "", "", ],
            ["||EU","http://ec.europa.eu/taxation_customs/customs/customs_controls/risk_management/customs_eu/index_fr.htm", "", "", "", "", "_blank", "", "", ],
            ["||Frankreich","http://www.douane.gouv.fr/menu.asp?id=511", "", "", "", "", "_blank", "", "", ],
            ["||Slovenia","http://e-uprava.gov.si/e-uprava/en/zivljenjskeSituacijeDrevo.euprava?dogodek.id=12485", "", "", "", "", "_blank", "", "", ],
         ["NOUS SOMMES","", "", "", "", "", "", "", "", ],
        ["|mentions légales  ","menue_call.php?go=impressum&dir=dyn", "", "", "", "", "", "", "", ],
        ["|CG","menue_call.php?go=agb_&dir=stat", "", "", "", "", "", "", "", ],
            ["support - L'aide","menue_call.php?go=support&dir=dyn", "", "", "", "", "", "", "", ],
      ["Presse","menue_call.php?go=presse&dir=dyn", "", "", "", "", "", "", "", ],  ["blogue  ","http://alpenentransit.blogspot.com", "", "", "", "", "_blank", "", "", ],
    ["plan du site","menue_call.php?go=atc_sitemap_&dir=stat", "", "", "", "", "", "", "", ],
        
 ];
/* ["|protection de Alpes","", "", "", "", "", "", "", "", ],
			["||monitraf","http://www.monitraf.org/102.html", "", "", "", "", "_blank", "", "", ],            
            ["||La Convention alpine","http://www.alpenkonvention.org/page1_fr", "", "", "", "", "_blank", "", "", ],
            ["||Cipra","http://cipra.4teamwork.ch/fr", "", "", "", "", "_blank", "", "", ],
            ["||initiative des alpes","http://www.initiative-des-alpes.ch/f/Actualite.asp", "", "", "", "", "_blank", "", "", ],
            ["||Conféderation de suisse","http://www.uvek.admin.ch/themen/umwelt/00640/00642/index.html?lang=fr", "", "", "", "", "_blank", "", "", ],
  */