var menuItems = [

    ["LA LORO AZINDA","", "", "", "", "", "0", "0", "", ],
        ["|Profilo","menue_call.php?go=tcontacts_data.inc&func=user_profile&dir=includes", "", "", "Bearbeiten Sie Ihre Kontaktdaten", "", "", "", "", ],
        ["|Parola d'accesso","menue_call.php?go=tcontacts_data.inc&func=user_password&dir=includes", "", "", "Neues Passwot eingeben", "", "", "", "", ],
        ["|Veicoli","", "", "", "", "", "", "", "", ],
            ["||Ancora entrando","menue_call.php?go=tkfz_data.inc&func=kfz_reg&dir=includes", "", "", "Neues Fahrzeug erfassen ?", "", "", "", "", ],
            ["||lavoro sopra","menue_call.php?go=tkfz_data.inc&func=kfz_list&dir=includes", "", "", "Daten eines erfassten Fahrzeugs Ã¤ndern ?", "", "", "", "", ],
        ["|Driver","", "", "", "", "", "", "", "", ],
            ["||Ancora entrando","menue_call.php?go=tpartner_data.inc&func=part_new&dir=includes", "", "", "Neuen Fahrer erfassen ?", "", "", "", "", ],
            ["||lavoro sopra","menue_call.php?go=tpartner_data.inc&func=part_list&dir=includes", "", "", "Daten eines erfassten Fahrers Ã¤ndern ?", "", "", "", "", ],
        ["|Itinerari","", "", "", "", "", "", "", "", ],
            ["||Offerta di trasporto","menue_call.php?go=ttourkfz_data.inc&func=tourkfz_reg&dir=includes", "", "", "Fracht angebot anpassen ?", "", "", "", "", ],
            ["||lavoro di trasporto sopra","menue_call.php?go=ttourkfz_data.inc&func=tourkfz_list&dir=includes", "", "", "Neuen Fahrer erfassen ?", "", "", "", "", ],
            ["||Offerta di veicolo","menue_call.php?go=ttourlad_data.inc&func=tourlad_reg&dir=includes", "", "", "Fahrzeug fÃ¼r Tour anbieten ?", "", "", "", "", ],
            ["||Lavoro di veicolo sopra","menue_call.php?go=ttourlad_data.inc&func=tourlad_list&dir=includes", "", "", "Fahrzeug angebot anpassen ?", "", "", "", "", ],
          ["||Offerta di rimozione","menue_call.php?go=tumz_data.inc&func=umz_reg&dir=includes", "", "", "Umzug Tour anbieten ?", "", "", "", "", ],
            ["||Lavoro di rimozione sopra","menue_call.php?go=tumz_data.inc&func=umz_list&dir=includes", "", "", "Umzug Angebot anpassen ?", "", "", "", "", ],
         ["|Cliente","menue_call.php?go=profil&dir=dyn", "", "", "", "", "", "", "", ],
       ["RICERCHE ANCORA","", "", "", "", "", "0", "", "", ],
        ["|del veicolo","menue_call.php?go=toursuchen_data.inc&func=such_list&value=kfz&dir=includes", "", "", "", "", "", "", "", ],
        ["|di trasporto","menue_call.php?go=toursuchen_data.inc&func=such_list&value=lad&dir=includes", "", "", "", "", "", "", "", ],
        ["|la rimozione","menue_call.php?go=toursuchen_data.inc&func=such_list&value=umz&dir=includes", "", "", "", "", "", "", "", ],
    ["GUIDA","", "", "", "", "", "0", "", "", ],
        ["|Nave delle merci","", "", "", "", "_parent", "", "", "", ],
            ["||DB Carico","http://www.railion.com/site/railion/en/start.html", "", "", "", "_blank", "", "", "", ],
            ["||SBB Carico","https://cis3.sbbcargo.ch/ciso/start.do?lang=it", "", "", "", "_blank", "", "", "", ],
            ["||Austria Carico","http://www.railcargo.at/en/index.jsp", "", "", "", "_blank", "", "", "", ],
            ["||SLOVENSKE Carico","http://www.sz-tovornipromet.si/en/", "", "", "", "_blank", "", "", "", ],
         ["||CHINA(Peking)","menue_call.php?go=china&dir=dyn", "", "", "", "_blank", "", "", "", ],
     ["|Treno di automobile","", "", "", "", "", "", "", "", ],
            ["||Treno di automobile","http://www.autoreisezuege-in-europa.de/", "", "", "", "_blank", "", "", "", ],
            ["||DB","http://www.dbautozug.de/site/dbautozug/it/start.html", "", "", "", "_blank", "", "", "", ],
            ["||SBB","http://mct.sbb.ch/mct/it/reiselust/europareisen/zuege-international-2/autoreisezug.htm", "", "", " ", "_blank", "", "", "", ],
     ["TRANSITO","", "", "", "", "", "0", "", "", ],
        ["|Riserva","menue_call.php?go=trans_reser&dir=dyn", "", "", "", "", "", "", "", ],
        ["|Abitudini","menue_call.php?go=profil&dir=dyn", "", "", "", "", "", "", "", ],
        ["|Richieste","menue_call.php?go=profil&dir=dyn", "", "", "", "_parent", "", "", "", ],
   ["GARANTI","", "", "", "", "", "0", "", "", ],
        ["|Info","menue_call.php?go=sponsor_info_&dir=stat", "", "", "", "", "", "", "", ],
        ["|Donazioni","menue_call.php?go=spenden&dir=dyn", "", "", "", "_parent", "", "", "", ],
];