var menuItems = [
    ["SINNE FIRME","", "", "", "", "", "0", "0", "", ],
        ["|Profil","menue_call.php?go=tcontacts_data.inc&func=user_profile&dir=includes", "", "", "Bearbeiten Sie Ihre Kontaktdaten", "", "", "", "", ],
        ["|mot de passe","menue_call.php?go=tcontacts_data.inc&func=user_password&dir=includes", "", "", "Neues Passwot eingeben", "", "", "", "", ],
        ["|Véhicule","", "", "", "", "", "", "", "", ],
            ["||taper qc.","menue_call.php?go=tkfz_data.inc&func=kfz_reg&dir=includes", "", "", "Neues Fahrzeug erfassen ?", "", "", "", "", ],
            ["||corroyer","menue_call.php?go=tkfz_data.inc&func=kfz_list&dir=includes", "", "", "Daten eines erfassten Fahrzeugs ÃƒÂ¤ndern ?", "", "", "", "", ],
        ["|Camionneur","", "", "", "", "", "", "", "", ],
            ["||taper qc.","menue_call.php?go=tpartner_data.inc&func=part_new&dir=includes", "", "", "Neuen Fahrer erfassen ?", "", "", "", "", ],
            ["||corroyer","menue_call.php?go=tpartner_data.inc&func=part_list&dir=includes", "", "", "Daten eines erfassten Fahrers ÃƒÂ¤ndern ?", "", "", "", "", ],
        ["|Randonnèe","", "", "", "", "", "", "", "", ],
            ["||offre cargaison ","menue_call.php?go=ttourkfz_data.inc&func=tourkfz_reg&dir=includes", "", "", "Fracht angebot anpassen ?", "", "", "", "", ],
            ["||corroyer cargaison","menue_call.php?go=ttourkfz_data.inc&func=tourkfz_list&dir=includes", "", "", "Neuen Fahrer erfassen ?", "", "", "", "", ],
            ["||offre véhicule","menue_call.php?go=ttourlad_data.inc&func=tourlad_reg&dir=includes", "", "", "Fahrzeug fÃƒÂ¼r Tour anbieten ?", "", "", "", "", ],
            ["||corroyer véhicule","menue_call.php?go=ttourlad_data.inc&func=tourlad_list&dir=includes", "", "", "Fahrzeug angebot anpassen ?", "", "", "", "", ],
         ["||Un déménagement offrir","menue_call.php?go=tumz_data.inc&func=umz_reg&dir=includes", "", "", "Umzug Tour anbieten ?", "", "", "", "", ],
            ["||Un déménagement travailler","menue_call.php?go=tumz_data.inc&func=umz_list&dir=includes", "", "", "Umzug Angebot anpassen ?", "", "", "", "", ],
          ["|Compte","menue_call.php?go=profil&dir=dyn", "", "", "", "", "", "", "", ],
    ["RECHERCHES","", "", "", "", "", "0", "", "", ],
        ["|véhicule","menue_call.php?go=toursuchen_data.inc&func=such_list&value=kfz&dir=includes", "", "", "", "", "", "", "", ],
        ["|cargaison","menue_call.php?go=toursuchen_data.inc&func=such_list&value=lad&dir=includes", "", "", "", "", "", "", "", ],
        ["|déménagement","menue_call.php?go=toursuchen_data.inc&func=such_list&value=umz&dir=includes", "", "", "", "", "", "", "", ],
    ["ÉCLISSE","", "", "", "", "", "0", "", "", ],
        ["|Expédition par chemin de fer","", "", "", "", "_parent", "", "", "", ],
            ["||Railion Logistics","http://www.railion.com/site/railion/fr/start.html", "", "", "", "_blank", "", "", "", ],
            ["||SBB Cargo","https://cis3.sbbcargo.ch/ciso/start.do?lang=fr", "", "", "", "_blank", "", "", "", ],
            ["||Austria Cargo","http://www.railcargo.at", "", "", "", "_blank", "", "", "", ],
            ["||SLOVENSKE Cargo","http://www.sz-tovornipromet.si/en/", "", "", "", "_blank", "", "", "", ],
        ["||CHINA(Peking)","menue_call.php?go=china&dir=dyn", "", "", "", "_blank", "", "", "", ],
      ["|Train d'autos accompagnées","", "", "", "", "", "", "", "", ],
            ["||Autoreisezuege","http://www.autoreisezuege-in-europa.de/", "", "", "", "_blank", "", "", "", ],
            ["||DB","http://www.dbautozug.de/site/dbautozug/fr/start.html", "", "", "", "_blank", "", "", "", ],
            ["||SBB","http://mct.sbb.ch/mct/fr/reiselust/europareisen/zuege-international-2/autoreisezug.htm", "", "", " ", "_blank", "", "", "", ],
        ["|Arrangement des contacts","menue_call.php?go=auftrag.php&dir=dyn", "", "", "", "_parent", "", "", "", ],
    ["TRANSIT","", "", "", "", "", "0", "", "", ],
        ["|réserver","menue_call.php?go=trans_reser&dir=dyn", "", "", "", "", "", "", "", ],
        ["|dédouanement","menue_call.php?go=profil&dir=dyn", "", "", "", "", "", "", "", ],
        ["|faire une demande","menue_call.php?go=profil&dir=dyn", "", "", "", "_parent", "", "", "", ],
    ["PARRAINEUR","", "", "", "", "", "0", "", "", ],
        ["|Info","menue_call.php?go=sponsor_info_&dir=stat", "", "", "", "", "", "", "", ],
        ["|Faire don","menue_call.php?go=spenden&dir=dyn", "", "", "", "_parent", "", "", "", ],
];